[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
requires-python = ">=3.10"
name = "reactors_czlab"
version = "2025.0.0"
description = "Bioreactor control module"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  {name = "Alexis Saldivar", email = "asaldivarg93@gmail.com"},
  {name = "Bhavana Palapati", email = "bpalapati0099@sdsu.edu"}
]
